[package]
name = "jist"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
regex = "1.10.6"
lazy_static = "1.5.0"
serde_json = "1.0"
json-tools = "*"